# Generated by Django 5.2 on 2025-01-15 10:00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_contactmessage_alter_notification_post_and_more'),
    ]

    operations = [
        # Remove existing FileField for User model
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        # Add new TextField for base64 image storage
        migrations.AddField(
            model_name='user',
            name='image_base64',
            field=models.TextField(
                blank=True,
                null=True,
                help_text='Base64 encoded image data'
            ),
        ),
        
        # Remove existing FileField for Post model
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        # Add new TextField for base64 image storage
        migrations.AddField(
            model_name='post',
            name='image_base64',
            field=models.TextField(
                blank=True,
                null=True,
                help_text='Base64 encoded image data'
            ),
        ),
    ]
