# Generated by Django 5.2 on 2025-08-10 15:30:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_convert_image_fields_to_base64'),
    ]

    operations = [
        # Remove the old FileField for Post model
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        # Add new TextField for base64 image storage
        migrations.AddField(
            model_name='post',
            name='image_base64',
            field=models.TextField(
                blank=True,
                null=True,
                help_text='Base64 encoded image data'
            ),
        ),
    ]
