version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: SZKblog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: S@y@n248
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      SECRET_KEY: 'your-secret-key'
      DEBUG: 'False'
      DATABASE_URL: postgres://postgres:S@y@n248@db:5432/SZKblog
      ALLOWED_HOSTS: 'localhost 127.0.0.1'
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: npm run dev

volumes:
  pgdata:
  static_volume:
  media_volume:
