services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.backend.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    plan: free
